---
- name: show version test
  hosts: test
  connection: local
  gather_facts: no

  tasks:
    - name: showver
      eos_command:
        commands: 
        - show version
        - show interfaces status
        provider: 
          username: admin
          password: admin
          host: "{{ inventory_hostname }}"
          transport: http
          use_ssl: no
          authorize: yes
          validate_certs: no
      register: out
    - debug: var=out.stdout_lines

#I'm making a change to the file to see how I push this in git!!! Pecker!
